from itertools import product

def build_index(ndim, *groups):
    """Build a multi-dimensional index tuple by mapping axis positions to values."""
    idx = [0] * ndim

    for axes, values in groups:
        for axis, value in zip(axes, values):
            idx[axis] = value

    return tuple(idx)

def indices(shape):
    """Yield all multi-dimensional index tuples for a given array shape."""
    if shape == ():
        yield ()
    else:
        yield from product(*(range(s) for s in shape))

def zeroes(shape):
    """Recursively create nested lists filled with zeros according to shape."""
    if len(shape) == 0:
        return 0

    return [zeroes(shape[1:]) for _ in range(shape[0])]

def set_nested(lst, idx, value):
    """Set value at a specific multi-dimensional index within nested lists."""
    if not idx:
        return value
    for i in idx[:-1]:
        lst = lst[i]
    lst[idx[-1]] = value
    return lst

# Deprecated: use Array.full instead.
def newarr(shape, fill):
    """Recursively create nested lists filled with values generated by fill function."""
    if len(shape) == 0:
        return fill()

    return [
        newarr(shape[1:], fill)
        for _ in range(shape[0])
    ]
